### ISSUE TITLE
Reproducible TeX build environment using Docker

### ISSUE THREAD

**Issue by ekangmonyet** [sysprog21/lkmpg#27]
This is to centralize efforts of developing Github Actions and **_if needed_** a customized docker container for the purpose of building all assets (PDFs, HTMLs, etc).

- [x] PDF Building (#28)
- [x] Existing release fix (#29 ~~or https://github.com/softprops/action-gh-release/pull/134~~)
- [x] HTML Building (#32 , ~~#20~~)

**Comment by ekangmonyet** [comment]
I think there's a cyclic dependency between this and #20 , my opinion is to merge #20 first, start this and improve HTML building at the same time.

**Comment by Hsins** [comment]
Just focus on "building docker image for consistent environment" and then the issue could be the first task to be done. The title of this issue are almost the same with #25.

**Comment by ekangmonyet** [comment]
I will focus on producing the PDF file first instead, since it is pretty stable and no other task dependencies. It will serve as a foundation to build other assets too.

**Comment by fennecJ** [comment]
For html building, the following script worked for me:
``` yml
name: Generate HTML and deploy to GitHub Page.

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: install dependencies and generating files
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make html

      - name: deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html                                          # --> should be the same as your output folder of make4ht
          publish_branch: gh-pages
```
And you can checkout the output in [here](https://fennecj.github.io/lkmpg/)
Looks like the page rendered well.
